### ISSUE TITLE
Lint error

### ISSUE THREAD

**Issue by eddiemoore** [amilajack/eslint-plugin-compat#30]
Running into this issue:
```shell
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at /XXX/node_modules/eslint-plugin-compat/lib/providers/CanIUseProvider.js:100:47
    at Array.filter (native)
    at getUnsupportedTargets (/XXX/node_modules/eslint-plugin-compat/lib/providers/CanIUseProvider.js:99:20)
    at Object.isValid (/XXX/node_modules/eslint-plugin-compat/lib/providers/CanIUseProvider.js:87:12)
    at /XXX/node_modules/eslint-plugin-compat/lib/Lint.js:57:20
    at Array.find (native)
    at Lint (/XXX/node_modules/eslint-plugin-compat/lib/Lint.js:56:6)
    at EventEmitter.lint (/XXX/node_modules/eslint-plugin-compat/lib/rules/compat.js:49:40)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

Testing against:
```js
const sw = navigator.serviceWorker
```
node v6.5.0
eslint v3.12.2
eslint-plugin-compat v0.1.3

**Comment by amilajack** [comment]
How are you configuring the plugin?

**Comment by eddiemoore** [comment]
```js
"plugins": [
  //
  "compat",
],
"rules": {
  //
  "compat/compat": 2,
},
"settings": {
  "targets": ["chrome", "firefox", "edge", "ie >= 11", "safari >= 9", "opera"],
  "polyfills": ["fetch"],
}
```

**Comment by amilajack** [comment]
At the moment, version operators aren't supported. See https://github.com/amilajack/eslint-plugin-compat/issues/24. Try removing the `>=` and let me know if that works

**Comment by eddiemoore** [comment]
Changed settings to
```js
"settings": {
    "targets": ["chrome", "firefox", "edge", "ie 11", "safari", "opera"],
    "polyfills": ["fetch"],
}
```
still get the same error

**Comment by eddiemoore** [comment]
I was going by what you have in the README. in the readme it shows the version numbers
