### ISSUE TITLE
Can we expect 3.8.0 to be released to npm soon?

### ISSUE THREAD

**Issue by rj-david** [amilajack/eslint-plugin-compat#332]
We are experiencing issues with 3.7.0 and have to fix the version to 3.6.0. We believe that 3.8.0 solves the problem. Thanks

**Comment by amilajack** [comment]
Can you please explain what issues you’re running into

**Comment by rj-david** [comment]
@amilajack 
```
navigator.serviceWorker() is not supported in android 81
```

**Comment by amilajack** [comment]
You can install the `next` tag, which is a prerelease of `3.8.0`:
```bash
yarn add --dev eslint-plugn-compat@next
npm install --save-dev eslint-plugn-compat@next
```
Let me know if this works for you! If you run into any issues I can reopen.

**Comment by rj-david** [comment]
@amilajack , got the following errors

```
TypeError: Cannot read property 'type' of undefined
Occurred while linting /home/rj/Projects/onepropertee/onepropertee-web-sellers/eslint-plugins/eslint-plugin-innovation-love/lib/rules/asset-url.js:37
    at /home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint-plugin-compat/lib/Lint.js:49:25
    at protoChainFromMemberExpression (/home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint-plugin-compat/lib/Lint.js:57:5)
    at /home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint-plugin-compat/lib/Lint.js:55:16
    at protoChainFromMemberExpression (/home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint-plugin-compat/lib/Lint.js:57:5)
    at lintMemberExpression (/home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint-plugin-compat/lib/Lint.js:66:27)
    at /home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/rj/Projects/onepropertee/onepropertee-web-sellers/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
```

No issues with 3.6.0
