### ISSUE TITLE
ReferenceError: Error while loading rule 'compat/compat': findUp is not defined

### ISSUE THREAD

**Issue by marekdedic** [amilajack/eslint-plugin-compat#528]
Hi,
I'm getting this error after updating to v4.1:

```
ReferenceError: Error while loading rule 'compat/compat': findUp is not defined
Occurred while linting /home/user/project/file.ts
    at isUsingTranspiler (/home/user/project/node_modules/eslint-plugin-compat/lib/rules/compat.js:79:22)
    at Object.create (/home/user/project/node_modules/eslint-plugin-compat/lib/rules/compat.js:134:241)
    at createRuleListeners (/home/user/project/node_modules/eslint/lib/linter/linter.js:926:21)
    at /home/user/project/node_modules/eslint/lib/linter/linter.js:1108:110
    at Array.forEach (<anonymous>)
    at runRules (/home/user/project/node_modules/eslint/lib/linter/linter.js:1045:34)
    at Linter._verifyWithoutProcessors (/home/user/project/node_modules/eslint/lib/linter/linter.js:1397:31)
    at Linter._verifyWithConfigArray (/home/user/project/node_modules/eslint/lib/linter/linter.js:1772:21)
    at Linter.verify (/home/user/project/node_modules/eslint/lib/linter/linter.js:1479:65)
    at Linter.verifyAndFix (/home/user/project/node_modules/eslint/lib/linter/linter.js:2031:29)
```

**Comment by yphoenix** [comment]
Seeing the same thing, reverted to 4.0.2

**Comment by RamonEspinosa** [comment]
I can work on this issue

**Comment by RamonEspinosa** [comment]
[Here](https://github.com/amilajack/eslint-plugin-compat/pull/529)'s a PR that solves this issue

**Comment by karudo** [comment]
This bug would not have occurred if **eslint** was properly set up in this project :-)

**Comment by yphoenix** [comment]
Meaning?

**Comment by ChuanyuWang** [comment]
> This bug would not have occurred if **eslint** was properly set up in this project :-)

may you share more details?

**Comment by muuvmuuv** [comment]
@ChuanyuWang this was meant to be a joke referring to this project "eslint-plugin-compat" not having eslint setup to report properties not available in a scope, in this case "findUp".

**Comment by yoyo837** [comment]
fixed in https://github.com/amilajack/eslint-plugin-compat/releases/tag/v4.1.1
